// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID `json:"id"`
	TokensUsed int32     `json:"tokens_used"`
	Version    int32     `json:"version"`
}
